# Generated by Django 4.1.7 on 2023-05-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_cart_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient_Recipe',
            new_name='IngredientRecipe',
        ),
    ]
