# Generated by Django 4.1.7 on 2023-03-28 07:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_ingredient_ingredient_recipe_ingredient_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_added_recipe_to_cart',
            field=models.ManyToManyField(related_name='recipes_in_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_favorited_currents_recipe',
            field=models.ManyToManyField(related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient_recipe',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
