# Generated by Django 4.1.7 on 2023-03-28 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_recipe_image_recipe_users_added_recipe_to_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='users_added_recipe_to_cart',
            field=models.ManyToManyField(blank=True, related_name='recipes_in_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users_favorited_currents_recipe',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
