# Generated by Django 4.1.7 on 2023-03-28 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileuser_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
