# Generated by Django 4.1.7 on 2023-03-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profileuser_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия пользователя'),
        ),
    ]
